### PR TITLE
Updated Jenkins Dockerfile to work with current get.docker.com script

### PR DESCRIPTION
**Pull request by tommysdk**

### CODE REVIEW

**Comment by tommysdk** [comment]
@andreschaffer Any thoughts on this? Seems to be a Mac specific issue.

**Comment by andreschaffer** [comment]
We want the same docker-engine version in the container as the host's since we are doing Docker-outisde-of-Docker.
We probably can get rid of that comparison logic though, since people should not be using too old docker versions at this point :)

Something like the following:

Update in run.sh (line 20):
`DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' | sed -En "s/-ce//p") docker-compose up -d`

Update in jenkins/Dockerfile (line 8):
`docker-engine=${DOCKER_VERSION}~ce-0~debian-jessie \`

Disclaimer: I only tested these changes on my Mac.
We might need a better replacement for the docker version in the scripts, since I noticed they have different suffixes depending on the OS. On Mac -> `17.03.1-ce`, on Linux (inside the container) -> `17.03.1~ce-0~debian-jessie`

**Comment by andreschaffer** [comment]
Would be good to have the replacement only in the Dockerfile

**Comment by tommysdk** [comment]
Yes, we should probably revise the comparison logic. Having it in one place would probably make things easier as well.

**Comment by andreschaffer** [comment]
Docker versions' names are making it quite hard to keep the same docker version in the container as in the host...
Suffix sometimes is debian, sometimes debian-jessie...

**Comment by andreschaffer** [comment]
Now it's not docker-engine anymore, but docker-ce too

**Comment by tommysdk** [comment]
@andreschaffer I'll try it out!

**Comment by andreschaffer** [comment]
Updated the Jenkins version and its plugins versions. 
Wasn't building anymore. My guess is some unpinned transitive dependency.

**Comment by tommysdk** [comment]
@andreschaffer it seems to work for me now!

**Comment by andreschaffer** [comment]
Alright, it's working on my machine :)
For some reason Jenkins doesn't start on Travis.
How is it working for you?

**Comment by andreschaffer** [comment]
Nice! Then we just need to fix it on Travis

**Comment by andreschaffer** [comment]
Added some logging for identifying the error cause and that's what we are getting on Travis:
```
jenkins_1  | touch: cannot touch ‘/var/jenkins_home/copy_reference_file.log’: Permission denied
jenkins_1  | Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
```

**Comment by andreschaffer** [comment]
On Travis:
```
Jenkins home permissions:
total 8.0K
4.0K drwxrwxr-x 2 travis travis 4.0K Jul  1 11:21 .
4.0K drwxrwxrwt 8 root   root   4.0K Jul  1 11:22 ..
```

**Comment by andreschaffer** [comment]
Fixed it :)

Small wrap-up:
- Moved from using host volumes mounting to docker data volumes for Gogs and Jenkins.
- Moved from using a tmp folder for the local repositories to a hidden (and ignored by Git) folder under the project itself (.repositories/).
- Bumped Jenkins and its plugins' versions.
- Limited retry attempts when waiting for containers to startup.
- Do not try to match host's and container's docker version anymore. This might become a problem we need to address in the future. Let's see how Docker versions' compatibility plays out.

**Comment by tommysdk** [comment]
@andreschaffer Great improvements! 👍

**Pull request merged**
